window.VERACelebrations = {
  G01: 'You now see groups where others see chaos.',
  G02: 'You now read visual families at a glance.',
  G03: 'You now complete patterns before they are whole.',
  G04: 'You now separate figure from noise with intent.',
  G05: 'You now guide eyes with continuous flow.',
  G06: 'You now trim complexity into clarity.',
  G07: 'You now map interfaces to mental expectations.',
  G08: 'You now reduce decision friction with structure.',
  G09: 'You now design targets that invite precision.',
  G10: 'You now shape memory load with discipline.',
  G11: 'You now orchestrate type for fast scanning.',
  G12: 'You now align rhythm that feels inevitable.',
  G13: 'You now calibrate contrast for readable systems.',
  G14: 'You now craft palettes that balance mood and utility.',
  G15: 'You now audit inclusively and fix with confidence.',
  G16: 'You now signal action before users hesitate.',
  G17: 'You now time motion with purpose and trust.',
  G18: 'You now place feedback where uncertainty begins.',
  G19: 'You now architect information that users can predict.',
  G20: 'You now detect manipulation and redesign ethically.',
};
